version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: boto3
    versions:
    - 1.17.12
    - 1.17.17
    - 1.17.22
    - 1.17.27
    - 1.17.3
    - 1.17.33
    - 1.17.39
    - 1.17.44
    - 1.17.49
    - 1.17.53
    - 1.17.7
  - dependency-name: cornice
    versions:
    - 5.1.0
  - dependency-name: jsonpatch
    versions:
    - "1.31"
  - dependency-name: pyramid
    versions:
    - 1.10.7
  - dependency-name: zope-interface
    versions:
    - 5.2.0
    - 5.3.0
